services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: sales-manager-app
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: sales-manager-db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: sales-manager-dev
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
